### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by zl7261** [likaia/chat-system#29]
Request URL: https://www.kaisir.cn/api/user/searchUserInfo
Request Method: POST

{"content":"123456i","userId":"d9b5b284940b43a2b7d43771296e3032"}

```json
{"code":0,"msg":"接口调用成功","data":[{"password":"21907605ee29a896bfd4bef9e3034cd3","gender":0,"createTime":"2021-02-05 17:44:26","onlineStatus":true,"avatarSrc":"https://www.kaisir.cn/uploads/b63d320649de4fc5bb22c06b04a97b6b.png","id":2032,"userName":"123456i","userId":"d9b5b284940b43a2b7d43771296e3032"}]}
```

通过cmd5撞库可得密码为 123456
![image](https://user-images.githubusercontent.com/27967791/107017743-81043480-67da-11eb-823f-a99093c443d4.png)

https://www.cmd5.com/hash.aspx?s=123456

**Comment by likaia** [comment]
啊 这，我大意了，谢谢反馈，我晚上修复下

**Comment by likaia** [comment]
问题已修复
